api/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from . import views

router = routers.DefaultRouter()
router.register(r"children", views.ChildViewSet)
router.register(r"changes", views.DiaperChangeViewSet)
router.register(r"feedings", views.FeedingViewSet)
router.register(r"notes", views.NoteViewSet)
router.register(r"sleep", views.SleepViewSet)
router.register(r"temperature", views.TemperatureViewSet)
router.register(r"timers", views.TimerViewSet)
router.register(r"tummy-times", views.TummyTimeViewSet)
router.register(r"weight", views.WeightViewSet)
router.register(r"height", views.HeightViewSet)
router.register(r"head-circumference", views.HeadCircumferenceViewSet)
router.register(r"bmi", views.BMIViewSet)

app_name = "api"

urlpatterns = [
    path("api/", include(router.urls)),
    path("api/auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "api/schema",
        get_schema_view(
            title="Baby Buddy API",
            version=1,
            description="API documentation for the Baby Buddy application",
        ),
        name="openapi-schema",
    ),
]

core/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("children/", views.ChildList.as_view(), name="child-list"),
    path("children/add/", views.ChildAdd.as_view(), name="child-add"),
    path("children/<str:slug>/", views.ChildDetail.as_view(), name="child"),
    path("children/<str:slug>/edit/", views.ChildUpdate.as_view(), name="child-update"),
    path(
        "children/<str:slug>/delete/", views.ChildDelete.as_view(), name="child-delete"
    ),
    path("timeline/", views.Timeline.as_view(), name="timeline"),
    path("changes/", views.DiaperChangeList.as_view(), name="diaperchange-list"),
    path("changes/add/", views.DiaperChangeAdd.as_view(), name="diaperchange-add"),
    path(
        "changes/<int:pk>/",
        views.DiaperChangeUpdate.as_view(),
        name="diaperchange-update",
    ),
    path(
        "changes/<int:pk>/delete/",
        views.DiaperChangeDelete.as_view(),
        name="diaperchange-delete",
    ),
    path("feedings/", views.FeedingList.as_view(), name="feeding-list"),
    path("feedings/add/", views.FeedingAdd.as_view(), name="feeding-add"),
    path("feedings/<int:pk>/", views.FeedingUpdate.as_view(), name="feeding-update"),
    path(
        "feedings/<int:pk>/delete/",
        views.FeedingDelete.as_view(),
        name="feeding-delete",
    ),
    path("notes/", views.NoteList.as_view(), name="note-list"),
    path("notes/add/", views.NoteAdd.as_view(), name="note-add"),
    path("notes/<int:pk>/", views.NoteUpdate.as_view(), name="note-update"),
    path("notes/<int:pk>/delete/", views.NoteDelete.as_view(), name="note-delete"),
    path("sleep/", views.SleepList.as_view(), name="sleep-list"),
    path("sleep/add/", views.SleepAdd.as_view(), name="sleep-add"),
    path("sleep/<int:pk>/", views.SleepUpdate.as_view(), name="sleep-update"),
    path("sleep/<int:pk>/delete/", views.SleepDelete.as_view(), name="sleep-delete"),
    path("temperature/", views.TemperatureList.as_view(), name="temperature-list"),
    path("temperature/add/", views.TemperatureAdd.as_view(), name="temperature-add"),
    path(
        "temperature/<int:pk>/",
        views.TemperatureUpdate.as_view(),
        name="temperature-update",
    ),
    path(
        "temperature/<int:pk>/delete/",
        views.TemperatureDelete.as_view(),
        name="temperature-delete",
    ),
    path("timers/", views.TimerList.as_view(), name="timer-list"),
    path("timers/add/", views.TimerAdd.as_view(), name="timer-add"),
    path("timers/add/quick/", views.TimerAddQuick.as_view(), name="timer-add-quick"),
    path("timers/<int:pk>/", views.TimerDetail.as_view(), name="timer-detail"),
    path("timers/<int:pk>/edit/", views.TimerUpdate.as_view(), name="timer-update"),
    path("timers/<int:pk>/delete/", views.TimerDelete.as_view(), name="timer-delete"),
    path("timers/<int:pk>/stop/", views.TimerStop.as_view(), name="timer-stop"),
    path(
        "timers/<int:pk>/restart/", views.TimerRestart.as_view(), name="timer-restart"
    ),
    path(
        "timers/delete-inactive/",
        views.TimerDeleteInactive.as_view(),
        name="timer-delete-inactive",
    ),
    path("tummy-time/", views.TummyTimeList.as_view(), name="tummytime-list"),
    path("tummy-time/add/", views.TummyTimeAdd.as_view(), name="tummytime-add"),
    path(
        "tummy-time/<int:pk>/", views.TummyTimeUpdate.as_view(), name="tummytime-update"
    ),
    path(
        "tummy-time/<int:pk>/delete/",
        views.TummyTimeDelete.as_view(),
        name="tummytime-delete",
    ),
    path("weight/", views.WeightList.as_view(), name="weight-list"),
    path("weight/add/", views.WeightAdd.as_view(), name="weight-add"),
    path("weight/<int:pk>/", views.WeightUpdate.as_view(), name="weight-update"),
    path("weight/<int:pk>/delete/", views.WeightDelete.as_view(), name="weight-delete"),
    path("height/", views.HeightList.as_view(), name="height-list"),
    path("height/add/", views.HeightAdd.as_view(), name="height-add"),
    path("height/<int:pk>/", views.HeightUpdate.as_view(), name="height-update"),
    path("height/<int:pk>/delete/", views.HeightDelete.as_view(), name="height-delete"),
    path(
        "head-circumference/",
        views.HeadCircumferenceList.as_view(),
        name="head-circumference-list",
    ),
    path(
        "head-circumference/add/",
        views.HeadCircumferenceAdd.as_view(),
        name="head-circumference-add",
    ),
    path(
        "head-circumference/<int:pk>/",
        views.HeadCircumferenceUpdate.as_view(),
        name="head-circumference-update",
    ),
    path(
        "head-circumference/<int:pk>/delete/",
        views.HeadCircumferenceDelete.as_view(),
        name="head-circumference-delete",
    ),
    path("bmi/", views.BMIList.as_view(), name="bmi-list"),
    path("bmi/add/", views.BMIAdd.as_view(), name="bmi-add"),
    path("bmi/<int:pk>/", views.BMIUpdate.as_view(), name="bmi-update"),
    path("bmi/<int:pk>/delete/", views.BMIDelete.as_view(), name="bmi-delete"),
]

reports/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = "reports"

urlpatterns = [
    path(
        "children/<str:slug>/reports",
        views.ChildReportList.as_view(),
        name="report-list",
    ),
    path(
        "children/<str:slug>/reports/changes/amounts/",
        views.DiaperChangeAmounts.as_view(),
        name="report-diaperchange-amounts-child",
    ),
    path(
        "children/<str:slug>/reports/changes/lifetimes/",
        views.DiaperChangeLifetimesChildReport.as_view(),
        name="report-diaperchange-lifetimes-child",
    ),
    path(
        "children/<str:slug>/reports/changes/types/",
        views.DiaperChangeTypesChildReport.as_view(),
        name="report-diaperchange-types-child",
    ),
    path(
        "children/<str:slug>/reports/feeding/amounts/",
        views.FeedingAmountsChildReport.as_view(),
        name="report-feeding-amounts-child",
    ),
    path(
        "children/<str:slug>/reports/feeding/duration/",
        views.FeedingDurationChildReport.as_view(),
        name="report-feeding-duration-child",
    ),
    path(
        "children/<str:slug>/reports/sleep/pattern/",
        views.SleepPatternChildReport.as_view(),
        name="report-sleep-pattern-child",
    ),
    path(
        "children/<str:slug>/reports/sleep/totals/",
        views.SleepTotalsChildReport.as_view(),
        name="report-sleep-totals-child",
    ),
    path(
        "children/<str:slug>/reports/tummytime/duration/",
        views.TummyTimeDurationChildReport.as_view(),
        name="report-tummytime-duration-child",
    ),
    path(
        "children/<str:slug>/reports/weight/weight/",
        views.WeightWeightChildReport.as_view(),
        name="report-weight-weight-child",
    ),
    path(
        "children/<str:slug>/reports/height/height/",
        views.HeightHeightChildReport.as_view(),
        name="report-height-height-child",
    ),
    path(
        "children/<str:slug>/reports/head-circumference/head-circumference/",
        views.HeadCircumferenceHeadCircumferenceChildReport.as_view(),
        name="report-head-circumference-head-circumference-child",
    ),
    path(
        "children/<str:slug>/reports/bmi/bmi/",
        views.BMIBMIChildReport.as_view(),
        name="report-bmi-bmi-child",
    ),
]

reports/views.py
# -*- coding: utf-8 -*-
from django.views.generic.detail import DetailView

from babybuddy.mixins import PermissionRequiredMixin
from core import models

from . import graphs


class ChildReportList(PermissionRequiredMixin, DetailView):
    """
    Listing of available reports for a child.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/report_list.html"


class DiaperChangeAmounts(PermissionRequiredMixin, DetailView):
    """
    Graph of diaper "amounts" - measurements of urine output.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/diaperchange_amounts.html"

    def get_context_data(self, **kwargs):
        context = super(DiaperChangeAmounts, self).get_context_data(**kwargs)
        child = context["object"]
        changes = models.DiaperChange.objects.filter(child=child, amount__gt=0)
        if changes and changes.count() > 0:
            context["html"], context["js"] = graphs.diaperchange_amounts(changes)
        return context


class DiaperChangeLifetimesChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of diaper "lifetimes" - time between diaper changes.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/diaperchange_lifetimes.html"

    def get_context_data(self, **kwargs):
        context = super(DiaperChangeLifetimesChildReport, self).get_context_data(
            **kwargs
        )
        child = context["object"]
        changes = models.DiaperChange.objects.filter(child=child)
        if changes and changes.count() > 1:
            context["html"], context["js"] = graphs.diaperchange_lifetimes(changes)
        return context


class DiaperChangeTypesChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of diaper changes by day and type.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/diaperchange_types.html"

    def get_context_data(self, **kwargs):
        context = super(DiaperChangeTypesChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        changes = models.DiaperChange.objects.filter(child=child)
        if changes:
            context["html"], context["js"] = graphs.diaperchange_types(changes)
        return context


class FeedingAmountsChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of daily feeding amounts over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/feeding_amounts.html"

    def __init__(self):
        super(FeedingAmountsChildReport, self).__init__()
        self.html = ""
        self.js = ""

    def get_context_data(self, **kwargs):
        context = super(FeedingAmountsChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        instances = models.Feeding.objects.filter(child=child)
        if instances:
            context["html"], context["js"] = graphs.feeding_amounts(instances)
        return context


class FeedingDurationChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of feeding durations over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/feeding_duration.html"

    def __init__(self):
        super(FeedingDurationChildReport, self).__init__()
        self.html = ""
        self.js = ""

    def get_context_data(self, **kwargs):
        context = super(FeedingDurationChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        instances = models.Feeding.objects.filter(child=child)
        if instances:
            context["html"], context["js"] = graphs.feeding_duration(instances)
        return context


class SleepPatternChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of sleep pattern comparing sleep to wake times by day.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/sleep_pattern.html"

    def __init__(self):
        super(SleepPatternChildReport, self).__init__()
        self.html = ""
        self.js = ""

    def get_context_data(self, **kwargs):
        context = super(SleepPatternChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        instances = models.Sleep.objects.filter(child=child).order_by("start")
        if instances:
            context["html"], context["js"] = graphs.sleep_pattern(instances)
        return context


class SleepTotalsChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of total sleep by day.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/sleep_totals.html"

    def __init__(self):
        super(SleepTotalsChildReport, self).__init__()
        self.html = ""
        self.js = ""

    def get_context_data(self, **kwargs):
        context = super(SleepTotalsChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        instances = models.Sleep.objects.filter(child=child).order_by("start")
        if instances:
            context["html"], context["js"] = graphs.sleep_totals(instances)
        return context


class TummyTimeDurationChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of tummy time durations over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/tummytime_duration.html"

    def __init__(self):
        super(TummyTimeDurationChildReport, self).__init__()
        self.html = ""
        self.js = ""

    def get_context_data(self, **kwargs):
        context = super(TummyTimeDurationChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        instances = models.TummyTime.objects.filter(child=child)
        if instances:
            context["html"], context["js"] = graphs.tummytime_duration(instances)
        return context


class WeightWeightChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of weight change over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/weight_change.html"

    def get_context_data(self, **kwargs):
        context = super(WeightWeightChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        objects = models.Weight.objects.filter(child=child)
        if objects:
            context["html"], context["js"] = graphs.weight_weight(objects)
        return context


class HeightHeightChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of height change over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/height_change.html"

    def get_context_data(self, **kwargs):
        context = super(HeightHeightChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        objects = models.Height.objects.filter(child=child)
        if objects:
            context["html"], context["js"] = graphs.height_height(objects)
        return context


class HeadCircumferenceHeadCircumferenceChildReport(
    PermissionRequiredMixin, DetailView
):
    """
    Graph of head circumference change over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/head_circumference_change.html"

    def get_context_data(self, **kwargs):
        context = super(
            HeadCircumferenceHeadCircumferenceChildReport, self
        ).get_context_data(**kwargs)
        child = context["object"]
        objects = models.HeadCircumference.objects.filter(child=child)
        if objects:
            (
                context["html"],
                context["js"],
            ) = graphs.head_circumference_head_circumference(objects)
        return context


class BMIBMIChildReport(PermissionRequiredMixin, DetailView):
    """
    Graph of BMI change over time.
    """

    model = models.Child
    permission_required = ("core.view_child",)
    template_name = "reports/bmi_change.html"

    def get_context_data(self, **kwargs):
        context = super(BMIBMIChildReport, self).get_context_data(**kwargs)
        child = context["object"]
        objects = models.BMI.objects.filter(child=child)
        if objects:
            context["html"], context["js"] = graphs.bmi_bmi(objects)
        return context

reports/templates/reports/base.html
{% extends 'babybuddy/page.html' %}
{% load i18n static %}

{% block title %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'core:child-list' %}">{% trans "Children" %}</a></li>
    <li class="breadcrumb-item font-weight-bold"><a href="{% url 'core:child' object.slug %}">{{ object }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'reports:report-list' object.slug %}">{% trans "Reports" %}</a></li>
{% endblock %}

reports/templates/reports/diaperchange_amounts.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Diaper Amounts" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Diaper Amounts" %}</li>
{% endblock %}

reports/templates/reports/diaperchange_lifetimes.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Diaper Lifetimes" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Diaper Lifetimes" %}</li>
{% endblock %}

reports/templates/reports/diaperchange_types.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Diaper Change Types" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Diaper Change Types" %}</li>
{% endblock %}

reports/templates/reports/feeding_amounts.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Feeding Amounts" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Feeding Amounts" %}</li>
{% endblock %}

reports/templates/reports/feeding_duration.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Average Feeding Durations" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Average Feeding Durations" %}</li>
{% endblock %}

reports/templates/reports/head_circumference_change.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Head Circumference" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Head Circumference" %}</li>
{% endblock %}

reports/templates/reports/height_change.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Height" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Height" %}</li>
{% endblock %}

reports/templates/reports/report_base.html
{% extends 'reports/base.html' %}
{% load i18n static %}

{% block title %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        {% if html %}
            {{ html|safe }}
        {% else %}
            <div class="jumbotron text-center">
                <i class="icon-sad" aria-hidden="true"></i>
                {% trans "There is not enough data to generate this report." %}
                <i class="icon-sad" aria-hidden="true"></i>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block javascript %}
    <script src="{% static "babybuddy/js/graph.js" %}"></script>
    <script>Plotly.setPlotConfig({locale: '{{ LOCALE }}'})</script>
    {{ js|safe }}
{% endblock %}

reports/templates/reports/report_list.html
{% extends 'reports/base.html' %}
{% load i18n static %}

{% block title %}{% trans "Reports" %} - {{ object }}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <h1>Reports</h1>
        <div class="list-group">
            <a href="{% url 'reports:report-bmi-bmi-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Body Mass Index (BMI)" %}</a>
            <a href="{% url 'reports:report-diaperchange-amounts-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Change Amounts" %}</a>
            <a href="{% url 'reports:report-diaperchange-types-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Change Types" %}</a>
            <a href="{% url 'reports:report-diaperchange-lifetimes-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Diaper Lifetimes" %}</a>
            <a href="{% url 'reports:report-feeding-amounts-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Feeding Amounts" %}</a>
            <a href="{% url 'reports:report-feeding-duration-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Feeding Durations (Average)" %}</a>
            <a href="{% url 'reports:report-head-circumference-head-circumference-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Head Circumference" %}</a>
            <a href="{% url 'reports:report-height-height-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Height" %}</a>
            <a href="{% url 'reports:report-sleep-pattern-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Sleep Pattern" %}</a>
            <a href="{% url 'reports:report-sleep-totals-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Sleep Totals" %}</a>
            <a href="{% url 'reports:report-tummytime-duration-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Tummy Time Durations (Sum)" %}</a>
            <a href="{% url 'reports:report-weight-weight-child' object.slug %}" class="list-group-item list-group-item-action">{% trans "Weight" %}</a>
        </div>
    </div>
{% endblock %}

reports/templates/reports/sleep_pattern.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Sleep Pattern" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Sleep Pattern" %}</li>
{% endblock %}

reports/templates/reports/sleep_totals.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Sleep Totals" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Sleep Totals" %}</li>
{% endblock %}

reports/templates/reports/tummytime_duration.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Total Tummy Time Durations" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Total Tummy Time Durations" %}</li>
{% endblock %}

reports/templates/reports/weight_change.html
{% extends 'reports/report_base.html' %}
{% load i18n %}

{% block title %}{% trans "Weight" %} - {{ object }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Weight" %}</li>
{% endblock %}