api/urls.py
# -*- coding: utf-8 -*-
from django.urls import include, path
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from . import views

router = routers.DefaultRouter()
router.register(r"children", views.ChildViewSet)
router.register(r"changes", views.DiaperChangeViewSet)
router.register(r"feedings", views.FeedingViewSet)
router.register(r"notes", views.NoteViewSet)
router.register(r"sleep", views.SleepViewSet)
router.register(r"temperature", views.TemperatureViewSet)
router.register(r"timers", views.TimerViewSet)
router.register(r"tummy-times", views.TummyTimeViewSet)
router.register(r"weight", views.WeightViewSet)
router.register(r"height", views.HeightViewSet)
router.register(r"head-circumference", views.HeadCircumferenceViewSet)
router.register(r"bmi", views.BMIViewSet)

app_name = "api"

urlpatterns = [
    path("api/", include(router.urls)),
    path("api/auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "api/schema",
        get_schema_view(
            title="Baby Buddy API",
            version=1,
            description="API documentation for the Baby Buddy application",
        ),
        name="openapi-schema",
    ),
]

babybuddy/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

from . import views

app_patterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path(
        "password_reset/", auth_views.PasswordResetView.as_view(), name="password_reset"
    ),
    path("", views.RootRouter.as_view(), name="root-router"),
    path("welcome/", views.Welcome.as_view(), name="welcome"),
    path("users/", views.UserList.as_view(), name="user-list"),
    path("users/add/", views.UserAdd.as_view(), name="user-add"),
    path("users/<int:pk>/edit/", views.UserUpdate.as_view(), name="user-update"),
    path("users/<int:pk>/delete/", views.UserDelete.as_view(), name="user-delete"),
    path("user/password/", views.UserPassword.as_view(), name="user-password"),
    path("user/settings/", views.UserSettings.as_view(), name="user-settings"),
]

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("api.urls", namespace="api")),
    path("", include((app_patterns, "babybuddy"), namespace="babybuddy")),
    path("user/lang", include("django.conf.urls.i18n")),
    path("", include("core.urls", namespace="core")),
    path("", include("dashboard.urls", namespace="dashboard")),
    path("", include("reports.urls", namespace="reports")),
]

if settings.DEBUG:  # pragma: no cover
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("children/", views.ChildList.as_view(), name="child-list"),
    path("children/add/", views.ChildAdd.as_view(), name="child-add"),
    path("children/<str:slug>/", views.ChildDetail.as_view(), name="child"),
    path("children/<str:slug>/edit/", views.ChildUpdate.as_view(), name="child-update"),
    path(
        "children/<str:slug>/delete/", views.ChildDelete.as_view(), name="child-delete"
    ),
    path("timeline/", views.Timeline.as_view(), name="timeline"),
    path("changes/", views.DiaperChangeList.as_view(), name="diaperchange-list"),
    path("changes/add/", views.DiaperChangeAdd.as_view(), name="diaperchange-add"),
    path(
        "changes/<int:pk>/",
        views.DiaperChangeUpdate.as_view(),
        name="diaperchange-update",
    ),
    path(
        "changes/<int:pk>/delete/",
        views.DiaperChangeDelete.as_view(),
        name="diaperchange-delete",
    ),
    path("feedings/", views.FeedingList.as_view(), name="feeding-list"),
    path("feedings/add/", views.FeedingAdd.as_view(), name="feeding-add"),
    path("feedings/<int:pk>/", views.FeedingUpdate.as_view(), name="feeding-update"),
    path(
        "feedings/<int:pk>/delete/",
        views.FeedingDelete.as_view(),
        name="feeding-delete",
    ),
    path("notes/", views.NoteList.as_view(), name="note-list"),
    path("notes/add/", views.NoteAdd.as_view(), name="note-add"),
    path("notes/<int:pk>/", views.NoteUpdate.as_view(), name="note-update"),
    path("notes/<int:pk>/delete/", views.NoteDelete.as_view(), name="note-delete"),
    path("sleep/", views.SleepList.as_view(), name="sleep-list"),
    path("sleep/add/", views.SleepAdd.as_view(), name="sleep-add"),
    path("sleep/<int:pk>/", views.SleepUpdate.as_view(), name="sleep-update"),
    path("sleep/<int:pk>/delete/", views.SleepDelete.as_view(), name="sleep-delete"),
    path("temperature/", views.TemperatureList.as_view(), name="temperature-list"),
    path("temperature/add/", views.TemperatureAdd.as_view(), name="temperature-add"),
    path(
        "temperature/<int:pk>/",
        views.TemperatureUpdate.as_view(),
        name="temperature-update",
    ),
    path(
        "temperature/<int:pk>/delete/",
        views.TemperatureDelete.as_view(),
        name="temperature-delete",
    ),
    path("timers/", views.TimerList.as_view(), name="timer-list"),
    path("timers/add/", views.TimerAdd.as_view(), name="timer-add"),
    path("timers/add/quick/", views.TimerAddQuick.as_view(), name="timer-add-quick"),
    path("timers/<int:pk>/", views.TimerDetail.as_view(), name="timer-detail"),
    path("timers/<int:pk>/edit/", views.TimerUpdate.as_view(), name="timer-update"),
    path("timers/<int:pk>/delete/", views.TimerDelete.as_view(), name="timer-delete"),
    path("timers/<int:pk>/stop/", views.TimerStop.as_view(), name="timer-stop"),
    path(
        "timers/<int:pk>/restart/", views.TimerRestart.as_view(), name="timer-restart"
    ),
    path(
        "timers/delete-inactive/",
        views.TimerDeleteInactive.as_view(),
        name="timer-delete-inactive",
    ),
    path("tummy-time/", views.TummyTimeList.as_view(), name="tummytime-list"),
    path("tummy-time/add/", views.TummyTimeAdd.as_view(), name="tummytime-add"),
    path(
        "tummy-time/<int:pk>/", views.TummyTimeUpdate.as_view(), name="tummytime-update"
    ),
    path(
        "tummy-time/<int:pk>/delete/",
        views.TummyTimeDelete.as_view(),
        name="tummytime-delete",
    ),
    path("weight/", views.WeightList.as_view(), name="weight-list"),
    path("weight/add/", views.WeightAdd.as_view(), name="weight-add"),
    path("weight/<int:pk>/", views.WeightUpdate.as_view(), name="weight-update"),
    path("weight/<int:pk>/delete/", views.WeightDelete.as_view(), name="weight-delete"),
    path("height/", views.HeightList.as_view(), name="height-list"),
    path("height/add/", views.HeightAdd.as_view(), name="height-add"),
    path("height/<int:pk>/", views.HeightUpdate.as_view(), name="height-update"),
    path("height/<int:pk>/delete/", views.HeightDelete.as_view(), name="height-delete"),
    path(
        "head-circumference/",
        views.HeadCircumferenceList.as_view(),
        name="head-circumference-list",
    ),
    path(
        "head-circumference/add/",
        views.HeadCircumferenceAdd.as_view(),
        name="head-circumference-add",
    ),
    path(
        "head-circumference/<int:pk>/",
        views.HeadCircumferenceUpdate.as_view(),
        name="head-circumference-update",
    ),
    path(
        "head-circumference/<int:pk>/delete/",
        views.HeadCircumferenceDelete.as_view(),
        name="head-circumference-delete",
    ),
    path("bmi/", views.BMIList.as_view(), name="bmi-list"),
    path("bmi/add/", views.BMIAdd.as_view(), name="bmi-add"),
    path("bmi/<int:pk>/", views.BMIUpdate.as_view(), name="bmi-update"),
    path("bmi/<int:pk>/delete/", views.BMIDelete.as_view(), name="bmi-delete"),
]

core/models.py
# -*- coding: utf-8 -*-
from datetime import timedelta

from django.conf import settings
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
from django.utils.text import format_lazy
from django.utils.translation import gettext_lazy as _


def validate_date(date, field_name):
    """
    Confirm that a date is not in the future.
    :param date: a timezone aware date instance.
    :param field_name: the name of the field being checked.
    :return:
    """
    if date and date > timezone.localdate():
        raise ValidationError(
            {field_name: _("Date can not be in the future.")}, code="date_invalid"
        )


def validate_duration(model, max_duration=timedelta(hours=24)):
    """
    Basic sanity checks for models with a duration
    :param model: a model instance with 'start' and 'end' attributes
    :param max_duration: maximum allowed duration between start and end time
    :return:
    """
    if model.start and model.end:
        if model.start > model.end:
            raise ValidationError(
                _("Start time must come before end time."), code="end_before_start"
            )
        if model.end - model.start > max_duration:
            raise ValidationError(_("Duration too long."), code="max_duration")


def validate_unique_period(queryset, model):
    """
    Confirm that model's start and end date do not intersect with other
    instances.
    :param queryset: a queryset of instances to check against.
    :param model: a model instance with 'start' and 'end' attributes
    :return:
    """
    if model.id:
        queryset = queryset.exclude(id=model.id)
    if model.start and model.end:
        if queryset.filter(start__lt=model.end, end__gt=model.start):
            raise ValidationError(
                _("Another entry intersects the specified time period."),
                code="period_intersection",
            )


def validate_time(time, field_name):
    """
    Confirm that a time is not in the future.
    :param time: a timezone aware datetime instance.
    :param field_name: the name of the field being checked.
    :return:
    """
    if time and time > timezone.localtime():
        raise ValidationError(
            {field_name: _("Date/time can not be in the future.")}, code="time_invalid"
        )


class Child(models.Model):
    model_name = "child"
    first_name = models.CharField(max_length=255, verbose_name=_("First name"))
    last_name = models.CharField(
        blank=True, max_length=255, verbose_name=_("Last name")
    )
    birth_date = models.DateField(blank=False, null=False, verbose_name=_("Birth date"))
    slug = models.SlugField(
        allow_unicode=True,
        blank=False,
        editable=False,
        max_length=100,
        unique=True,
        verbose_name=_("Slug"),
    )
    picture = models.ImageField(
        blank=True, null=True, upload_to="child/picture/", verbose_name=_("Picture")
    )

    objects = models.Manager()

    cache_key_count = "core.child.count"

    class Meta:
        default_permissions = ("view", "add", "change", "delete")
        ordering = ["last_name", "first_name"]
        verbose_name = _("Child")
        verbose_name_plural = _("Children")

    def __str__(self):
        return self.name()

    def save(self, *args, **kwargs):
        self.slug = slugify(self, allow_unicode=True)
        super(Child, self).save(*args, **kwargs)
        cache.set(self.cache_key_count, Child.objects.count(), None)

    def delete(self, using=None, keep_parents=False):
        super(Child, self).delete(using, keep_parents)
        cache.set(self.cache_key_count, Child.objects.count(), None)

    def name(self, reverse=False):
        if not self.last_name:
            return self.first_name
        if reverse:
            return "{}, {}".format(self.last_name, self.first_name)
        return "{} {}".format(self.first_name, self.last_name)

    @classmethod
    def count(cls):
        """Get a (cached) count of total number of Child instances."""
        return cache.get_or_set(cls.cache_key_count, Child.objects.count, None)


class DiaperChange(models.Model):
    model_name = "diaperchange"
    child = models.ForeignKey(
        "Child",
        on_delete=models.CASCADE,
        related_name="diaper_change",
        verbose_name=_("Child"),
    )
    time = models.DateTimeField(blank=False, null=False, verbose_name=_("Time"))
    wet = models.BooleanField(verbose_name=_("Wet"))
    solid = models.BooleanField(verbose_name=_("Solid"))
    color = models.CharField(
        blank=True,
        choices=[
            ("black", _("Black")),
            ("brown", _("Brown")),
            ("green", _("Green")),
            ("yellow", _("Yellow")),
        ],
        max_length=255,
        verbose_name=_("Color"),
    )
    amount = models.FloatField(blank=True, null=True, verbose_name=_("Amount"))
    notes = models.TextField(blank=True, null=True, verbose_name=_("Notes"))

    objects = models.Manager()

    class Meta:
        default_permissions = ("view", "add", "change", "delete")
        ordering = ["-time"]
        verbose_name = _("Diaper Change")
        verbose_name_plural = _("Diaper Changes")

    def __str__(self):
        return str(_("Diaper Change"))

    def attributes(self):
        attributes = []
        if self.wet:
            attributes.append(self._meta.get_field("wet").verbose_name)
        if self.solid:
            attributes.append(self._meta.get_field("solid").verbose_name)
        if self.color:
            attributes.append(self.get_color_display())
        return attributes

    def clean(self):
        validate_time(self.time, "time")

        # One or both of Wet and Solid is required.
        if not self.wet and not self.solid:
            raise ValidationError(
                _("Wet and/or solid is required."), code="wet_or_solid"
            )


class Feeding(models.Model):
    model_name = "feeding"
    child = models.ForeignKey(
        "Child",
        on_delete=models.CASCADE,
        related_name="feeding",
        verbose_name=_("Child"),
    )
    start = models.DateTimeField(blank=False, null=False, verbose_name=_("Start time"))
    end = models.DateTimeField(blank=False, null=False, verbose_name=_("End time"))
    duration = models.DurationField(
        editable=False, null=True, verbose_name=_("Duration")
    )
    type = models.CharField(
        choices=[
            ("breast milk", _("Breast milk")),
            ("formula", _("Formula")),
            ("fortified breast milk", _("Fortified breast milk")),
            ("solid food", _("Solid food")),
        ],
        max_length=255,
        verbose_name=_("Type"),
    )
    method = models.CharField(
        choices=[
            ("bottle", _("Bottle")),
            ("left breast", _("Left breast")),
            ("right breast", _("Right breast")),
            ("both breasts", _("Both breasts")),
            ("parent fed", _("Parent fed")),
            ("self fed", _("Self fed")),
        ],
        max_length=255,
        verbose_name=_("Method"),
    )
    amount = models.FloatField(blank=True, null=True, verbose_name=_("Amount"))
    notes = models.TextField(blank=True, null=True, verbose_name=_("Notes"))

    objects = models.Manager()

    class Meta:
        default_permissions = ("view", "add", "change", "delete")
        ordering = ["-start"]
        verbose_name = _("Feeding")
        verbose_name_plural = _("Feedings")

    def __str__(self):
        return str(_("Feeding"))

    def save(self, *args, **kwargs):
        if self.start and self.end:
            self.duration = self.end - self.start
        super(Feeding, self).save(*args, **kwargs)

    def clean(self):
        validate_time(self.start, "start")
        validate_time(self.end, "end")
        validate_duration(self)
        validate_unique_period(Feeding.objects.filter(child=self.child), self)


class Note(models.Model):
    model_name = "note"
    child = models.ForeignKey(
        "Child", on_delete=models.CASCADE, related_name="note", verbose_name=_("Child")
    )
    note = models.TextField(verbose_name=_("Note"))
    time = models.DateTimeField(
        default=timezone.now, blank=False, verbose_name=_("Time")
    )

    objects = models.Manager()

    class Meta:
        default_permissions = ("view", "add", "change", "delete")
        ordering = ["-time"]
        verbose_name = _("Note")
        verbose_name_plural = _("Notes")

    def __str__(self):
        return str(_("Note"))


class NapsManager(models.Manager):
    def get_queryset(self):
        qs = super(NapsManager, self).get_queryset()
        return qs.filter(id__in=[obj.id for obj in qs if obj.nap])


class Sleep(models.Model):
    model_name = "sleep"
    child = models.ForeignKey(
        "Child", on_delete=models.CASCADE, related_name="sleep", verbose_name=_("Child")
    )
    napping = models.BooleanField(editable=False, null=True, verbose_name=_("Napping"))
    start = models.DateTimeField(blank=False, null=False, verbose_name=_("Start time"))
    end = models.DateTimeField(blank=False, null=False, verbose_name=_("End time"))
    duration = models.DurationField(
        editable=False, null=True, verbose_name=_("Duration")
    )
    notes = models.TextField(blank=True, null=True, verbose_name=_("Notes"))

    objects = models.Manager()
    naps = NapsManager()

    class Meta:
        default_permissions = ("view", "add", "change", "delete")
        ordering = ["-start"]
        verbose_name = _("Sleep")
        verbose_name_plural = _("Sleep")

    def __str__(self):
        return str(_("Sleep"))

    @property
    def nap(self):
        nap_start_min = timezone.datetime.strptime(
            settings.BABY_BUDDY["NAP_START_MIN"], "%H:%M"
        ).time()
        nap_start_max = timezone.datetime.strptime(

babybuddy/templates/babybuddy/base.html
{% load babybuddy_tags i18n static %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_locale as LOCALE %}
{% get_current_timezone as TIMEZONE %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %} | Baby Buddy</title>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "babybuddy/root/apple-touch-icon.png" %}?v=20211218" />
    <link rel="apple-touch-startup-image" href="{% static "babybuddy/root/apple-touch-startup-image.png" %}?v=20211218" />
    <link rel="icon" type="image/svg+xml" href="{% static "babybuddy/root/favicon.svg" %}?v=20210925" />
    <link rel="manifest" href="{% static "babybuddy/root/site.webmanifest" %}?v=20211225" />
    <link rel="mask-icon" href="{% static "babybuddy/root/safari-pinned-tab.svg" %}?v=20211218" color="#37abe9" />
    <link rel="shortcut icon" href="{% static "babybuddy/root/favicon.ico" %}?v=20211218" />
    <link rel="stylesheet" href="{% static "babybuddy/css/app.css" %}" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-title" content="Baby Buddy" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta name="application-name" content="Baby Buddy" />
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="msapplication-navbutton-color" content="#37abe9">
    <meta name="msapplication-starturl" content="/">
    <meta name="msapplication-TileColor" content="#37abe9" />
    <meta name="theme-color" content="#37abe9" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
</head>
<body>

{% block nav %}{% endblock %}

{% block breadcrumb_nav %}
    <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href={% url "babybuddy:root-router" %}>{% trans "Home" %}</a></li>
            {% block breadcrumbs %}{% endblock %}
        </ol>
    </nav>
{% endblock %}

{% block page %}{% endblock %}

    <script src="{% static "babybuddy/js/vendor.js" %}"></script>
    <script>moment.locale('{{ LOCALE }}');</script>
    <script>moment.tz.setDefault('{{ TIMEZONE }}');</script>
    <script src="{% static "babybuddy/js/app.js" %}"></script>
    {% if user.is_authenticated %}
        <script>BabyBuddy.PullToRefresh.init()</script>
    {% endif %}

{% block javascript %}{% endblock %}
</body>
</html>

babybuddy/templates/babybuddy/form.html
{% load i18n widget_tweaks %}

<div class="container-fluid pb-5">
    <form role="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group row">
                {% include 'babybuddy/form_field.html' %}
            </div>
        {% endfor %}
        <button type="submit" class="submit-primary btn btn-primary btn-lg">{% trans "Submit" %}</button>
    </form>
</div>

babybuddy/templates/babybuddy/page.html
{% extends 'babybuddy/nav-dropdown.html' %}
{% load static timers %}

{% block page %}
    <div id="view-{{ request.resolver_match.view_name }}" class="container-fluid">
        <div class="row justify-content-md-center">
            <div class="col-lg-12 mb-4">
                {% include 'babybuddy/messages.html' %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

babybuddy/templates/babybuddy/user_confirm_delete.html
{% extends 'babybuddy/page.html' %}
{% load i18n widget_tweaks %}

{% block title %}{% trans "Delete User" %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'babybuddy:user-list' %}">{% trans "Users" %}</a></li>
    <li class="breadcrumb-item">{{ object }}</li>
    <li class="breadcrumb-item active" aria-current="page">{% trans "Delete" %}</li>
{% endblock %}

{% block content %}
    <form role="form" method="post">
        {% csrf_token %}
        {% blocktrans trimmed %}
            <h1>Are you sure you want to delete <span class="text-info">{{ object }}</span>?</h1>
        {% endblocktrans %}
        <input type="submit" value="{% trans "Delete" %}" class="btn btn-danger" />
        <a href="{% url 'babybuddy:user-list' %}" class="btn btn-default">{% trans "Cancel" %}</a>
    </form>
{% endblock %}

babybuddy/templates/babybuddy/user_form.html
{% extends 'babybuddy/page.html' %}
{% load i18n %}

{% block title %}
    {% if object %}
        {{ object }}
    {% else %}
        {% trans "Create User" %}
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'babybuddy:user-list' %}">{% trans "Users" %}</a></li>
    {% if object %}
        <li class="breadcrumb-item font-weight-bold">{{ object }}</li>
        <li class="breadcrumb-item active" aria-current="page">{% trans "Update" %}</li>
    {% else %}
        <li class="breadcrumb-item active" aria-current="page">{% trans "Create User" %}</li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if object %}
        {% blocktrans trimmed %}
            <h1>Update <span class="text-info">{{ object }}</span></h1>
        {% endblocktrans %}
    {% else %}
        <h1>{% trans "Create User" %}</h1>
    {% endif %}
    {% include 'babybuddy/form.html' %}
{% endblock %}

babybuddy/templates/babybuddy/user_list.html
{% extends 'babybuddy/page.html' %}
{% load bootstrap i18n widget_tweaks %}

{% block title %}{% trans "Users" %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Users" %}</li>
{% endblock %}

{% block content %}
    <h1>Users</h1>
    {% include 'babybuddy/filter.html' %}
    <div class="table-responsive">
        <table class="table table-striped table-hover user-list">
            <thead class="thead-inverse">
                <tr>
                    <th>{% trans "User" %}</th>
                    <th>{% trans "First Name" %}</th>
                    <th>{% trans "Last Name" %}</th>
                    <th>{% trans "Email" %}</th>
                    <th>{% trans "Staff" %}</th>
                    <th>{% trans "Active" %}</th>
                    <th class="text-center">{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <th scope="row">{{ object.username }}</th>
                        <td>{{ object.first_name }}</td>
                        <td>{{ object.last_name }}</td>
                        <td>{{ object.email }}</td>
                        <td>{{ object.is_staff|bool_icon }}</td>
                        <td>{{ object.is_active|bool_icon }}</td>
                        <td class="text-center">
                            <div class="btn-group btn-group-sm" role="group" aria-label="Actions">

                                {% if perms.admin.change_user %}
                                    <a href="{% url 'babybuddy:user-update' object.id %}" class="btn btn-warning">
                                        <i class="icon-update" aria-hidden="true"></i>
                                    </a>
                                {% endif %}

                                {% if perms.admin.delete_user %}
                                    <a href="{% url 'babybuddy:user-delete' object.id %}" class="btn btn-danger">
                                        <i class="icon-delete" aria-hidden="true"></i>
                                    </a>
                                {% endif %}

                            </div>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <th colspan="4">{% trans "No users found." %}</th>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% include 'babybuddy/paginator.html' %}

    {% if perms.admin.add_user %}
        <a href="{% url 'babybuddy:user-add' %}" class="btn btn-sm btn-success">
            <i class="icon-add" aria-hidden="true"></i> {% trans "Create User" %}
        </a>
    {% endif %}

{% endblock %}

babybuddy/templates/babybuddy/welcome.html
{% extends 'babybuddy/page.html' %}
{% load i18n widget_tweaks %}

{% block title %}{% trans "Welcome!" %}{% endblock %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active" aria-current="page">{% trans "Welcome!" %}</li>
{% endblock %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">{% trans "Welcome to Baby Buddy!" %}</h1>
        <p class="lead">
            {% blocktrans trimmed%}
                Learn about and predict baby's needs without (<em>as much</em>)
                guess work by using Baby Buddy to track &mdash;
            {% endblocktrans %}
        </p>
        <hr class="my-4">
        <div class="card-deck">
            <div class="card card-diaperchange">
                <div class="card-header text-center">
                    <i class="icon-2x icon-diaperchange" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                    <h3 class="card-title text-center">{% trans "Diaper Changes" %}</h3>
                </div>
            </div>
            <div class="card card-feeding">
                <div class="card-header text-center">
                    <i class="icon-2x icon-feeding" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                    <h3 class="card-title text-center">{% trans "Feedings" %}</h3>
                </div>
            </div>
            <div class="card card-sleep">
                <div class="card-header text-center">
                    <i class="icon-2x icon-sleep" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                    <h3 class="card-title text-center">{% trans "Sleep" %}</h3>
                </div>
            </div>
            <div class="card card-tummytime">
                <div class="card-header text-center">
                    <i class="icon-2x icon-tummytime" aria-hidden="true"></i>
                </div>
                <div class="card-body">
                    <h3 class="card-title text-center">{% trans "Tummy Time" %}</h3>
                </div>
            </div>
        </div>
        <hr class="my-4">
        <p class="lead">
            {% blocktrans trimmed %}
                As the amount of entries grows, Baby Buddy will help parents
                and caregivers to identify small patterns in baby's habits
                using the dashboard and graphs. Baby Buddy is mobile-friendly
                and uses a dark theme to help weary moms and dads with 2AM
                feedings and changings. To get started, just click the button
                below to add your first (or second, third, etc.) child!
            {% endblocktrans %}
        </p>
        <p class="text-center">
            {% if perms.core.add_child %}
                <a href="{% url 'core:child-add' %}" class="btn btn-lg btn-success">
                    <i class="icon-child" aria-hidden="true"></i> {% trans "Add a Child" %}
                </a>
            {% endif %}
        </p>
    </div>
{% endblock %}